# Generated by Django 4.2.7 on 2023-11-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField()),
                ('product_app', models.TextField()),
                ('category', models.CharField(choices=[('ML', 'Milk'), ('CK', 'Choklet'), ('BT', 'Butter'), ('CP', 'Chips'), ('BG', 'Burger'), ('PZ', 'Pizza'), ('GE', 'Ghee'), ('CD', 'Curd')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
